dvcrn/proton

src/proton/layers/git/core.cljs
* move to next hunk <kbd>SPC g d n</kbd>
* move to previous hunk <kbd>SPC g d N</kbd>
* show diff list  <kbd>SPC g d l</kbd>
=> Added keybindings for git-diff package.

project.clj, src/cljs/proton/core.cljs, src/dev/build.clj
=> shadow-build port

src/cljs/proton/core.cljs, src/cljs/proton/layers/lang/latex/README.md, src/cljs/proton/layers/lang/latex/core.cljs
I'm very new to clojure (only used to contribute here) so I'm open to suggestions on the best way to add to the packages list based on a config value. I copied the pattern used in core for installing the nuclide packages.
=> added latex layer

src/cljs/proton/layers/tools/git/core.cljs
Not sure if we go through with this. Feel free to test
=> added atomatigit support, refs #36

src/cljs/proton/layers/core/packages.cljs
Added [file-icons](https://atom.io/packages/file-icons) package.
=> Added file-icons package to core layer, refs #23.

src/cljs/proton/core.cljs, src/cljs/proton/layers/core/actions.cljs, src/cljs/proton/layers/lang/markdown/README.md, src/cljs/proton/layers/lang/markdown/core.cljs
@dvcrn to test this changes you need to apply https://github.com/dvcrn/proton/pull/46 first. Please merge this after https://github.com/dvcrn/proton/pull/46 will be merged. Thanks.
=> Added markdown layer.

HOW-TO-LAYER.md, plugin/templates/proton.edn, src/cljs/proton/core.cljs, src/cljs/proton/layers/base.cljs, src/cljs/proton/layers/core/core.cljs, src/cljs/proton/layers/fun/power_mode/core.cljs, src/cljs/proton/layers/lang/clojure/README.md, src/cljs/proton/layers/lang/clojure/core.cljs, src/cljs/proton/layers/lang/elixir/core.cljs, src/cljs/proton/layers/lang/julia/core.cljs, src/cljs/proton/layers/lang/latex/core.cljs, src/cljs/proton/layers/lang/markdown/core.cljs, src/cljs/proton/layers/lang/python/README.md, src/cljs/proton/layers/lang/python/core.cljs, src/cljs/proton/layers/tools/git/core.cljs, src/cljs/proton/layers/tools/linter/README.md, src/cljs/proton/layers/tools/linter/core.cljs, src/cljs/proton/layers/tools/minimap/core.cljs, src/cljs/proton/lib/atom.cljs, src/cljs/proton/lib/helpers.cljs, src/cljs/proton/lib/package_manager.cljs, src/cljs/proton/lib/proton.cljs
Refs https://github.com/dvcrn/proton/issues/50.
We need to check how we could deal with linters that automatically install `Linter`. In particular the [clojure linter](https://github.com/AtomLinter/linter-clojure) does this, but solving this problem will be very helpful later on
=> Linter support

src/cljs/proton/layers/lang/julia/core.cljs
Lots of recent action on the julia plugins. Most of it is reflected here
=> Update julia mode-keybindings

src/cljs/proton/core.cljs, src/cljs/proton/layers/tools/build/README.md, src/cljs/proton/layers/tools/build/core.cljs
Adds build layer in the flavor of the linter layer.
=> added build layer

src/cljs/proton/config/editor.cljs, src/cljs/proton/core.cljs, src/cljs/proton/layers/core/README.md, src/cljs/proton/layers/core/actions.cljs, src/cljs/proton/layers/core/core.cljs, src/cljs/proton/layers/core/keybindings.cljs
Changes affected `:core` layer.
- Added category __UI toggles/themes__ bind to `SPC T`
- Added keybinding `SPC T M` toggle maximize window.
- Toggle full screen keybinding moved to `SPC T F`
- Added `theme-switch` package to core layer.
- Added keybinding `SPC T n` to cycle theme using `theme-switch:next`
command.
- User defined `core.themes` config also included to theme cycling.
will be added to `theme-switch.profiles` configuration.
=> Added toggle maximize and theme-switch package.

src/cljs/proton/core.cljs, src/cljs/proton/layers/frameworks/django/README.md, src/cljs/proton/layers/frameworks/django/core.cljs, src/cljs/proton/layers/lang/python/README.md, src/cljs/proton/layers/lang/python/core.cljs
- Added packages python-isort, python-tools
- Added new mode key bindings.
=> Python lang layer improvements.

src/cljs/proton/layers/core/README.md, src/cljs/proton/layers/core/core.cljs, src/cljs/proton/layers/core/keybindings.cljs, src/cljs/proton/layers/core/packages.cljs, src/cljs/proton/lib/proton.cljs
- Added key binding `SPC SPC` to start easy-motion by letter.
=> Added easy-motion-redux package to core layer.

plugin/styles/proton.less, src/cljs/proton/core.cljs, src/cljs/proton/lib/helpers.cljs
=> Display executed keystrokes and selected category.

src/cljs/proton/core.cljs, src/cljs/proton/layers/core/packages.cljs, src/cljs/proton/layers/lang/html/README.md, src/cljs/proton/layers/lang/html/core.cljs
Layer includes markup and style langs.
Added `autocomplete-paths` to core packages.
=> Created basic html layer.

src/cljs/proton/layers/lang/typescript/core.cljs
Fix tslint registration, I think.  Sorry about that!
=> Properly register tslint in typescript layer

src/cljs/proton/core.cljs, src/cljs/proton/layers/lang/ruby/README.md, src/cljs/proton/layers/lang/ruby/core.cljs
Not a ruby guy. If you have any feedback, please feel free to add! :)
=> added ruby layer

src/cljs/proton/layers/core/keybindings.cljs
My mistake - it should have been `window:save-all` instead of `core:save-all`.
=> Fix SPC f S aka save all

plugin/templates/proton.edn, src/cljs/proton/layers/core/core.cljs, src/cljs/proton/layers/core/packages.cljs
Experimental new theme. Please submit feedback or ideas to this PR
=> Theme change

src/cljs/proton/layers/core/keybindings.cljs
Now targets buffers within pane
=> Fixes "kill other buffers" closing other panes

plugin/templates/proton.edn, src/cljs/proton/core.cljs, src/cljs/proton/lib/atom.cljs, src/cljs/proton/lib/package_manager.cljs
Left to add some docs and comments...
Please test this one.
=> Added configuration option to disable packages

src/cljs/proton/layers/core/keybindings.cljs, src/cljs/proton/layers/core/packages.cljs
Adds the following shortcuts:
`SPC w -` split pane down
`SPC w /` split pane right
`SPC w H` move pane left
`SPC w J` move pane down
`SPC w K` move pane up
`SPC w L` move pane right
Adds the package `move-panes`
=> Window shortcuts

.github/CONTRIBUTING.md
Please add your ideas here
/cc @geksilla @Lknechtli
=> Contribution guidelines

src/cljs/proton/core.cljs, src/cljs/proton/layers/lang/haskell/README.md, src/cljs/proton/layers/lang/haskell/core.cljs
Status: ready for review.
~~Todo: I need feedback and to use all the features to make sure they work.~~
=> Add haskell language layer

src/cljs/proton/core.cljs, src/cljs/proton/layers/lang/swift/README.md, src/cljs/proton/layers/lang/swift/core.cljs
=> Swift layer

README.md
proton is no longer a early attempt. Some of the text was still hinting
to things that were no longer up to date. I also took the time to clean
it up a little bit.
=> doc(README): add TOC, modernize text

plugin/styles/proton.less, src/cljs/proton/core.cljs, src/cljs/proton/layers/core/README.md, src/cljs/proton/layers/core/core.cljs, src/cljs/proton/lib/atom.cljs
Added option `proton.core.whichKeyDelay` to core layer.
ping @spencerlyon2  to check this out.
=> feat(core): Added which-key delay option.

src/cljs/proton/layers/lang/elixir/README.md, src/cljs/proton/layers/lang/elixir/core.cljs, src/cljs/proton/lib/helpers.cljs
* Added atom-elixir package to elixir layer.
* Moved iex keybindings to `s` category.
* Added more commands related to iex.
* Removed autocomplete-elixr package.
=> feat(elixir): Added atom-elixir package and layer refactoring.

src/cljs/proton/layers/lang/javascript/README.md, src/cljs/proton/layers/lang/javascript/core.cljs
Fixed issue with tern keybindings.
Added keybinding to show documentation at cursor.
=> fix(javascript): Tern keybindings don't work.

src/cljs/proton/layers/lang/clojure/core.cljs
Very minor; hope I've got all the paperwork right! 📝
=> fix(clojure): correct proto-repl test command

src/cljs/proton/core.cljs, src/cljs/proton/layers/apps/notes/README.md, src/cljs/proton/layers/apps/notes/core.cljs
* Added `:apps/notes` layer based on nvatom package.
* Added appropriate key binding `SPC a n` to toggle notes list view.
* Added Readme.
=> feat(apps/notes): Provide notes management application.

plugin/templates/proton.edn
=> Updated github links

src/cljs/proton/lib/helpers.cljs
Detected this issue on Linux + zsh. Child process which executes `/bin/zsh -ic env; exit` doesn't terminate and hangs.
=> fix(core): Shell process doesn't terminate on fixing PATH variable.

src/cljs/proton/lib/atom.cljs, src/cljs/proton/lib/package_manager.cljs
@dvcrn, please check this implementation. Thanks.
=> fix(core): Ignore name case for package management.

src/cljs/proton/layers/core/keybindings.cljs
=> feat(bufferNativateion): added buffer navigation

src/cljs/proton/core.cljs, src/cljs/proton/layers/frameworks/react/README.md, src/cljs/proton/layers/frameworks/react/core.cljs, src/cljs/proton/layers/lang/javascript/README.md, src/cljs/proton/layers/lang/javascript/core.cljs
This addresses #226 
I've moved react to a new frameworks layer called 'react' :)
=> moved react to new frameworks layer
