- src/proton/layers/core/core.cljs
* added files category keybinding followed by <kbd>SPC f</kbd>
* added atom specific category keybindings followed by <kbd>SPC f a</kbd>
* open atom dotfile <kbd>SPC f a d</kbd>
* open dev-tools <kbd>SPC f a c</kbd>
* reload editor <kbd>SPC f a R</kbd>
> Added files category and atom specific keybindings.

- src/proton/layers/core/core.cljs
This commit adds autocomplete item movement via <kbd>Ctrl j</kbd>, <kbd>Ctrl k</kbd>.
> Fixed ctrl-j ctrl-k keybindings for autocomplete.

- src/proton/layers/core/core.cljs
The tabs toggle was manually only applying the toggle to the first tab-bar in the document -- now it maps over all of them.
Also added toggles for the gutter and to go to/from fullscreen.
> Fixed tab toggle and added toggle for gutter/fullscreen

- src/proton/core.cljs
- src/proton/layers/core/core.cljs
- src/proton/lib/atom.cljs
- src/proton/lib/package_manager.cljs
- `disable-package` now checks if a package is already disabled before attempting to disable it (resulted in duplicate `disabledPackages` entries before)
- Excluded `disabledPackages` from config wipe
- Changed `relative-numbers` and `tabs` to new disable/enable package logic
> Add support for disabling / enabling packages during layer init

- src/cljs/proton/core.cljs
- src/cljs/proton/layers/tools/minimap/README.md
- src/cljs/proton/layers/tools/minimap/core.cljs
- src/cljs/proton/lib/atom.cljs
- src/cljs/proton/lib/proton.cljs
Supersedes #15 
New layer to install minimap. Also added a toggle under `<spc> t m`
NOTE: this somewhat duplicates the `deep-merge` application from #28 - the changes are identical, so I don't think this should cause any problems if both are merged.
> added minimap layer

- HOW-TO-LAYER.md
- src/cljs/proton/core.cljs
- src/cljs/proton/layers/base.cljs
- src/cljs/proton/layers/core/core.cljs
- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/layers/lang/clojure/README.md
- src/cljs/proton/layers/lang/clojure/core.cljs
- src/cljs/proton/layers/lang/julia/core.cljs
- src/cljs/proton/layers/lang/latex/core.cljs
- src/cljs/proton/layers/lang/python/core.cljs
- src/cljs/proton/layers/tools/git/core.cljs
- src/cljs/proton/layers/tools/minimap/core.cljs
- src/cljs/proton/lib/atom.cljs
- src/cljs/proton/lib/mode.cljs
- src/cljs/proton/lib/proton.cljs
Implemented basic **mode** functionality.
Added function to define mode with extra info.
Prefer to use inside `init-layer!` function, for example:
```clojure
;; src/proton/layers/clojure
(defmethod init-layer! :clojure
[_ config]
;; define mode name
(mode/define-mode :clojure 
;; initialize for selected editor grammar
:atom-grammars ["Clojure"] 
;; or initialize for file extension
:file-extensions [#"\.proton$"]
;; custom init function on mode activation
:init (fn []
(atom-env/set-grammar "Clojure")))
;; define mode keybindings
;; also able to define within define-mode function using :mode-keybindings keyword
;; this one 
(mode/define-keybindings :clojure
{:t {:category "toggles"
:p {:action "parinfer:toggleMode" :title "Toggle Parinfer Mode"}}})
;; same as
(mode/define-mode :clojure …
```
> Simple mode implementation + mode keybindings

- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/layers/core/packages.cljs
This kinda goes along with the theme of #23 as well as the concept of matching spacemacs more
The `spc f e` category is in the flavor of spacemacs (`spc f e d` opens `~/.proton` in atom but `~/.spacemacs` in emacs). We already have some some things like this in the meta category (`spc _`) so we'd have to consider if we want to follow their path or make our own.
However, I really like `advanced-open-file` and think it is a great fit for `spc f f` (that is the part of this PR that addresses #23)
> added advanced new file and f keymap category

- src/cljs/proton/lib/mode.cljs
Get mode keybindings by editor id instead of grammar.
> Fix mode keybindings are empty.

- src/cljs/proton/layers/tools/git/README.md
- src/cljs/proton/layers/tools/git/core.cljs
Added packages:
- blame
- git-history
- merge-conflicts
Added keybindgs:
- `SPC g b` - toggle blame
- `SPC g l` - git log
- `SPC g L` - git log for current file
- `SPC g h` - git history for current file
Little refactor. Use get-active-editor from proton.layers.core.actions.
Updated Readme. Added Key Bindings and Configuration sections.
> Added new packages and keybindings for git layer.

- src/cljs/proton/lib/atom.cljs
This will allow to pass string selector using `:target` for keybinding. For example:
```clj
{ :g { 
:d {
:t { :action "git-diff-details:toggle-git-diff-details" :target "atom-text-editor.is-focused"}}}}
```
> Allow pass selector as :target to keybinding.

- src/cljs/proton/layers/core/core.cljs
Another change for https://github.com/dvcrn/proton/issues/23
Material is way too big by default. I tweaked it a bit to make a more solid default:
changes to
Changes:
* Smaller tabs
* Smaller file-tree
* More colorful accent color
* Icon on active tab
* Slight contrast for panels
> Theme tweaks

- src/cljs/proton/layers/lang/latex/README.md
- src/cljs/proton/layers/lang/latex/core.cljs
handle latex config in a cleaner way.
Before we were `concat`ing onto an atom each time the config was parsed. Now we just set the value of an atom with the info from the config value.
> update latex config

- src/cljs/proton/core.cljs
- src/cljs/proton/layers/core/core.cljs
After init we have a 3 second timeout before closing the modal window. 
This PR lets the user set the duration of that time out using the config variable `proton.core.post-init-timeout`
I don't love the name and it should probably be documented somewhere, but it works for me!
> added config for timout after init

- plugin/styles/proton.less
- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/lib/pane_manager.cljs
ping @dvcrn, @spencerlyon2  to review.
> Added pane focus specific keybindings. refs #65

- src/cljs/proton/core.cljs
- src/cljs/proton/lib/package_manager.cljs
Force activated themes cause mess with `core.themes` config.
In my `.proton` I have few themes `:additional-packages` *dracula-ui*, *dracula-theme*, *slime* and appropriate config `["core.themes" ["dracula-ui" "dracula-theme"]]`.  When proton activates themes `core.themes` config become:
```js
atom.config.get('core.themes')
["slime", "dracula-theme", "dracula-ui", "atom-material-syntax", "atom-material-ui", "dracula-ui", "dracula-theme"]
```
> Skip force activation for themes.

- src/cljs/proton/lib/package_manager.cljs
Sometimes after new package installed I get js error regarding calling `isTheme` method on undefined.
> Fix check for package status before type checking.

- src/cljs/proton/lib/keymap.cljs
Fixed warnings regarding referencing to proton.core.mode-keymaps and proton.lib.mode.get-current-editor-mode.
> Fix keymap.cljs compilation warnings. fix #85

- HOW-TO-LAYER.md
- src/cljs/proton/core.cljs
- src/cljs/proton/layers/base.cljs
- src/cljs/proton/layers/core/core.cljs
- src/cljs/proton/layers/lang/clojure/core.cljs
- src/cljs/proton/layers/lang/javascript/core.cljs
- src/cljs/proton/layers/lang/julia/core.cljs
- src/cljs/proton/lib/atom.cljs
- src/cljs/proton/lib/keymap.cljs
- src/cljs/proton/lib/mode.cljs
- src/cljs/proton/lib/package_manager.cljs
- src/cljs/proton/lib/proton.cljs
- Added proto-repl package and appropriate mode keybindings.
- Added layer method `init-package` dispatched by vector [:layer-name
:package-name]
- Atom specific variables moved from proton.core namespace to
proton.lib.atom
- Added observers on package disable/enable state.
- `proton.lib.pakackage_manager/enable-package` now executes `package-init`
hook for associated package.
- `proton.lib.package_manager/disable-package` removes appropriate
keybindings defined for associated package. Also removes mode defined
for package from `proton.lib.mode/modes`
- Added `proton.lib.mode/define-package-mode` method to define mode
based on package name.
- Added conventional method `proton.lib.mode/package-mode-name` to
generate mode name for specified package.
- Added `proton.lib.mode/link-modes` …
> Added proto-repl package, mode improvements.

- src/cljs/proton/layers/core/README.md
- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/layers/core/packages.cljs
Added [expand-region](https://atom.io/packages/expand-region) package and binded `expand-region:expand` action to `SPC v`. Also added next toggles:
- `SPC ;` toggle comments
- `SPC t g` renamed and remaped to `SPC t n`
- `SPC t n` renamed and remaped to `SPC t r`
- `SPC t w` toggle whitespace
- `SPC t i` toggle indent guides
- `SPC t I` toggle auto indent
- `SPC T m` toggle menu bar
> Added more toggles keybindings and expand-region.

- src/cljs/proton/layers/lang/rust/core.cljs
Indentation error in keybindings for rust language
> fix indent error in rust layer

- src/cljs/proton/config/editor.cljs
- src/cljs/proton/layers/core/README.md
- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/layers/core/packages.cljs
- Window movements via j,k,l,h moved to `SPC w` category to be
consistent with spacemacs key bindings.
- Added *maximize-pane* package.
- Maximize pane binded to `SPC w m`.
- Added key binding `SPC w c` to close active pane.
- Close other pane key binding moved to `SPC w o`.
- *theme-switch* package moved to `proton.layers.core.packages`.
> Winow keybindings improvements.

- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/layers/lang/python/core.cljs
When two panes opened and we have visible two or more editors left editor will be always passed as target to dispatch atom commands when selector string is used as `:target`.
> Fixed issue when only left editor marked as target.

- src/cljs/proton/layers/core/README.md
- src/cljs/proton/layers/core/keybindings.cljs
Available actions:
- <kbd>spc s e</kbd> : select all words matching current selected word (or under cursor)
- <kbd>spc s n</kbd> : select next word
- <kbd>spc s s</kbd> : skip next word
- <kbd>spc s u</kbd> : undo last select
> Added :s category for selection

- src/cljs/proton/layers/tools/git/README.md
- src/cljs/proton/layers/tools/git/core.cljs
Removed keybindings:
- `g S` (git-plus status is not needed anymore)
Changed keybindings
- `g b` -> `g B` (normal b is better for branching and big B for blaming)
- `g c` -> `g c c` (commit is now a separate category)
New keybindings:
- `g S` - stash category
- `g A` - add all files
- `g p` - git pull
- `g b` - branch category
- `g f` - git fetch
- `g m` - git merge
- `g r` - git rebase
ETC:
- `q` is now closing automatigit when open
> added new git keybindings

- README.md
- src/cljs/proton/core.cljs
- src/cljs/proton/layers/core/README.md
- src/cljs/proton/layers/core/core.cljs
"proton.core.wipeUserConfigs" is a boolean. Default value is `true`
which means that atom configurations always reset when proton starts.
> Added option "proton.core.wipeUserConfigs".

- plugin/templates/proton.edn
- src/cljs/proton/core.cljs
- src/cljs/proton/layers/tools/bookmarks/README.md
- src/cljs/proton/layers/tools/bookmarks/core.cljs
Just some menu options for the core bookmarks package. I'm not sure this justifies its own layer since it doesn't actually install any new packages. Is this something that should belong in the core layer instead?
Also updated the `proton.edn` with this layer and the csharp layer (which I forgot to do in my last PR).
> Bookmarks Layer

- plugin/templates/proton.edn
- src/cljs/proton/layers/core/README.md
- src/cljs/proton/layers/core/core.cljs
- src/cljs/proton/layers/core/packages.cljs
- src/cljs/proton/layers/tools/linter/README.md
- src/cljs/proton/layers/tools/linter/core.cljs
With the recent change to single package nuclide, our nuclide integration no longer works. We need to either 
a) break out nuclide
b) replace nuclide with the unified package (https://github.com/dvcrn/proton/issues/101)
As a short term fix I removed `nuclide-file-watcher` which is the only nuclide package we use inside core and breaks immediately.
> Remove faulty nuclide modules

- src/cljs/proton/lib/helpers.cljs
For me error was thrown due to empty value of __LC_CTYPE__ variable on Mac.
> Prevent error caused by ENV variables without values

- src/cljs/proton/layers/core/keybindings.cljs
I was hoping to add more functionality (e.g. change dictionary), but [spell-check](https://github.com/atom/spell-check) hasn't implemented many of features yet.
I was also going to add a keybinding for "correct spelling", but spell-check uses a popup that shadows any further `SPC` actions. That means you have to use `CTRL+SHIFT+:" to exit the spell-check popup ಠ__ಠ .
As an alternative, I was considering binding `ESC` to `core:cancel`. If you like, I can add that. So it would be `SPC e c` perhaps to correct current word spelling, and then `ESC` to cancel.
Btw, to test changes, should I just build the local proton git repository?
> Add simple toggle for spell-check

- src/cljs/proton/layers/core/keybindings.cljs
I find myself trying to use `SPC f s` all of the time. I also added `SPC f S` to save all files in the window.
> Add file save to file sub keybinding

- src/cljs/proton/layers/lang/elixir/core.cljs
The author of `elixir-docs` has abandoned it and removed it so this no longer works with the `:lang/elixir` layer.
https://github.com/Psvensso/elixir-docs#-deprecated-
This removes the package and the keybindings.
I'm not familiar with clojurescript syntax so this needs to be verified. :)
> Remove deprecated elixir-docs

- src/cljs/proton/layers/core/keybindings.cljs
`SPC w u` is a nice shortcut when you accidentally close a pane. Used it far too often in Spacemacs. :)
> Window close undo

- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/layers/core/packages.cljs
Needs testing as I'm not sure how to run this locally.
I think the keybindings should work but I'm not 100% sure.
> Add highlight-line toggle to core

- src/cljs/proton/layers/lang/clojure/core.cljs
Since proto-repl 0.13.0 `inlineResults` configuration enabled by default.
> Added ink package to clojure layer

- src/cljs/proton/layers/core/keybindings.cljs
Previously, it closed the window, not the buffer (to use emacs terms)
> Fix close buffer keybinding

- src/cljs/proton/core.cljs
- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/lib/helpers.cljs
Following symbols affected:
- ; as :semicolon
- : as :colon
- / as :slash
So these symbols should be used in key bindings inside `.proton` and across the layers.
> Handle disallowed keywords chars with aliases. Fix #156

- src/cljs/proton/core.cljs
- src/cljs/proton/lib/atom.cljs
- src/cljs/proton/lib/helpers.cljs
There is no way to specify `scopeSelector` option for configurations
specified in `.proton`. Added 3-rd optional value with _hash-map_ type passed to
configuration. For example in `.proton`
```
;; .proton
...
:configuration
[
["editor.tabLength" 2 {:scopeSelector [".source.python" ".source.ruby"]}]
]
```
> fix(configuration): add option to specify scopeSelector

- src/cljs/proton/lib/atom.cljs
- src/cljs/proton/lib/keymap.cljs
This adds support for executing multiple actions with one keybindings.
The donation is a vector. If the command is a vector instead of a map, it will execute all maps inside the vector
> added support for multi actions for keybindings

- src/cljs/proton/layers/lang/html/core.cljs
`autoclose-html.additionalGrammars` config was removed since 0.22.0
version. We used this config to setup XML specific grammars.
Refs #173
> fix(html/autoclose-html): Remove init-package hook for autoclose-html package

- src/cljs/proton/layers/core/keybindings.cljs
`move-pane` bindings were cluttering the root namespace. Since this is usually a action that is not that commonly performed, It is better to have it under `w` only and not in the root space as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dvcrn/proton/175)
> refactor(core): remove `move-pane` bindings from root

- src/cljs/proton/core.cljs
- src/cljs/proton/lib/package_manager.cljs
When user remove some layer from `.proton` and reloads atom, packages
associated with removed layer should be removed but were installed.
> fix(package_manager): remove packages for layers

- .github/CONTRIBUTING.md
- src/cljs/proton/layers/lang/python/README.md
- src/cljs/proton/layers/lang/python/core.cljs
Flake8 includes pep8 and more;
- PyFlakes
- pep8
- Ned Batchelder’s McCabe script
> refactor(lang/python): replace pep8 linter with flake8

- src/cljs/proton/layers/lang/markdown/README.md
- src/cljs/proton/layers/lang/markdown/core.cljs
Add [atom-mdtoc](http://atom.io/packages/atom-mdtoc) for automatic TOC generation.
> feat(lang/markdown): add markdown-toc

- src/cljs/proton/lib/atom.cljs
All better; forgot I hadn't updated from upstream! 😅
> fix(*): add escaping to apm path

- src/cljs/proton/layers/tools/terminal/core.cljs
It should fix #225 .
The only problem I have locally is that `'` binding - it does not work for me (it didn't work with `terminal-plus` either). If I replace it with some other character i.e. `a`:
```clojure
{:a {:action "platformio-ide-terminal:toggle"
:title "terminal"}})
```
It works. Is there something wrong with my local config?
> Replaced terminal-plus package with platformio-ide-terminal

- plugin/templates/proton.edn
- src/cljs/proton/config/editor.cljs
- src/cljs/proton/core.cljs
- src/cljs/proton/layers/core/README.md
- src/cljs/proton/layers/core/core.cljs
- src/cljs/proton/lib/atom.cljs
- src/cljs/proton/lib/helpers.cljs
- src/cljs/proton/lib/proton.cljs
* Added option `proton.core.inputProvider` with default value `:vim-mode-plus`. Available options are `:vim-mode-plus`, `:vim-mode`, `:atomic-emacs`, `:default`
* Added deprecated warning for `proton.core.vim-provider` option.
* Added options `proton.core.leaderKey` and `proton.core.modeKey` to configure leader and major mode alias keystrokes
* Added info regarding `proton.core.leaderKey`, `proton.core.modeKey`, `proton.core.inputProvider` to core layer Readme.
@dvcrn review please.
> feat(core): Provide option to chose input mode for non-vim users.

- project.clj
There were namespace conflicts within atom with other plugins written in
clojurescript. On request, @thheller fixed the issue in shadow-build.
> Update shadow-build to fix dev-repl namespace

- src/cljs/proton/layers/core/keybindings.cljs
Seems like a useful thing to include in `+window`. `SPC w n` now creates a new Atom window. I also renamed some uses of the word. Now "window" consistently refers to the entire window, and each window may contain multiple "panes" which can be manipulated from `SPC w ...`
> Add `SPC w n` keybinding for a new window

- src/cljs/proton/core.cljs
- src/cljs/proton/layers/tools/expose/README.md
- src/cljs/proton/layers/tools/expose/core.cljs
Adds the `:tools/expose` layer for exposé, which provides a nice graphical buffer switch. If the minimap is installed, it shows a preview too. The keybinding is <kbd>SPC b e</kbd>.
> feat(tools/expose): add exposé buffer switching

- MANUAL.md
Previously undocumented feature where you can specify a CSS selector
as the `:target` key of a keymapping inside `.proton` is now
documented with an example.
> docs(MANUAL): document :target for keybindings

- src/cljs/proton/lib/helpers.cljs
which-key not appearing because of changes related to event target
passed to command dispatcher. In this particular case event target
was `input.class-hidden` instead of `atom-text-editor.vim-mode-plus`.
Changes related to removing shadow dom from atom.
@dvcrn, @richarddewit can you please test this changes?
> fix(core): which-key panel not appearing in Atom 1.13.0

- MANUAL.md
- src/cljs/proton/core.cljs
- src/cljs/proton/layers/core/README.md
- src/cljs/proton/layers/core/core.cljs
[Updated PR description describing latest version of the behaviour]
Added a configuration option to skip showing the welcoming dialog box if there are no packages to add
or remove.
By default the welcome screen is still always shown, to enable the new behaviour set
`proton.core.alwaysShowWelcomeScreen` to false.
> feat(core): Skip welcome unless package changes

- src/cljs/proton/layers/tools/linter/README.md
- src/cljs/proton/layers/tools/linter/core.cljs
* Linter v2 has following dependencies linter-ui-default, intentsions and busy-signal
which will be removed since they are not included in tools/linter layer.
* Updated keybinding actions
> fix(tools/linter) changed commands and packages according latest linter

- src/cljs/proton/layers/lang/go/core.cljs
- don't show the go-debug panel by default
- move rename keybinding from `m r n` to `m r`
- fix rename binding executing the wrong command
work in progress, don't merge yet.
> Improve go-layer

- plugin/styles/proton.less
Some external themes were messing with the spacing of the modal panel by
setting paddings and margins. This adds !important rules to make sure
the spacing looks the same on all themes.
> fix(modal): force modal spacing to all themes

- src/cljs/proton/layers/core/packages.cljs
Solves issue #269
I think we just need to remove the package, it seemed like an easy PR
> remove :environment from core layer because of deprecation of package

- src/cljs/proton/layers/core/core.cljs
vim-mode-plus-ex-mode plugin suggests that you should use basic ex-mode instead of this plugin. 
On first ':' the plugin does not start, but shows this message 
> "Use ex-mode if you want better ex-mode then uninstall this package,"
in an info popup, all susequent ':' work as expected. 
This is quite annoying...
This pull request removes vim-mode-plus-ex-mode and replaces it with regular ex-mode.
In addition default keybinding for "vim-mode-plus-ext-mode" are removed since they are no longer needed.
> fix(core):remove vim-mode-plus-ex-mode

- src/cljs/proton/layers/lang/clojure/README.md
- src/cljs/proton/layers/lang/clojure/core.cljs
* fixed parinfer toggle mode command name
* added parinfer:disable keymap to `SPC m T d`
* fixed parinfer package name now lowercased
> fix(clojure): parinfer keybindings stop working

- src/cljs/proton/layers/apps/notes/README.md
- src/cljs/proton/layers/apps/notes/core.cljs
**Note:** to migrate configs from `nv-atom` just replace package name with `atom-notes` e.g. `nv-atom.directory` -> `atom-notes.directory`.
> fix(tools/notes): replace nv-atom package with atom-notes

- src/cljs/proton/layers/core/keybindings.cljs
- src/cljs/proton/lib/pane_manager.cljs
Make it so that SPC 1-9 goes to the first 9 panes, and SPC 0 goes to treeview.
In order to be robust if it can't find a pane it will go to treeview.
Now ignores 'panels' entirely, I'm not sure what they are and panes are what
is working for me.
This fixes #272 for me.
WRT 'panels' please let me know if I've overlooked something. In my editor panels for 'left' and 'right' were always empty anyway.
> fix(core) #272 SPC-# now works as expected
